import { getProfileDb } from "./db";
import { aiGenerationTraces } from "../db/schema/profile";
import { getActiveCharacterCreationCycle } from "./character-creation-cycle.service";
import { resolveActivePrompt } from "./prompt-runtime.service";
import { generateTextWithLlm } from "./text-llm-gateway.service";

export interface CharacterIdentitySuggestion { key:string; name:string; identity:string; traits:[string,string,string]; fitReason:string }
export interface CharacterIdentitySuggestionResult { suggestions:CharacterIdentitySuggestion[]; trace:{promptKey:string;promptVersion:number;provider:string;model:string;promptTokens:number|null;completionTokens:number|null;totalTokens:number|null;latencyMs:number} }
function parse(raw:string):CharacterIdentitySuggestion[]{const cleaned=raw.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");let value:unknown;try{value=JSON.parse(cleaned)}catch{throw new Error("LLM_OUTPUT_INVALID_JSON")}if(!value||typeof value!=="object"||!Array.isArray((value as {suggestions?:unknown}).suggestions))throw new Error("LLM_OUTPUT_SCHEMA_INVALID");const rows=(value as {suggestions:unknown[]}).suggestions;if(rows.length!==4)throw new Error("LLM_OUTPUT_SCHEMA_INVALID");return rows.map(row=>{if(!row||typeof row!=="object")throw new Error("LLM_OUTPUT_SCHEMA_INVALID");const r=row as Record<string,unknown>;for(const k of ["key","name","identity","fitReason"])if(typeof r[k]!=="string"||!(r[k] as string).trim())throw new Error("LLM_OUTPUT_SCHEMA_INVALID");if(!Array.isArray(r.traits)||r.traits.length!==3||!r.traits.every(v=>typeof v==="string"&&v.trim()))throw new Error("LLM_OUTPUT_SCHEMA_INVALID");return {key:String(r.key),name:String(r.name),identity:String(r.identity),traits:r.traits as [string,string,string],fitReason:String(r.fitReason)}})}
export async function generateCharacterIdentitySuggestions(userId:string,input:{householdId:string;childProfileId:string}):Promise<CharacterIdentitySuggestionResult>{const cycle=await getActiveCharacterCreationCycle(userId,input.householdId,input.childProfileId);if(!cycle)throw new Error("CHARACTER_CREATION_CYCLE_REQUIRED");const summary=(cycle.latestSummary??{}) as Record<string,unknown>;if(typeof summary.worldFeeling!=="string"||!summary.characterArchetype)throw new Error("CHARACTER_IDENTITY_CONTEXT_REQUIRED");const context={worldFeeling:summary.worldFeeling,characterArchetype:summary.characterArchetype,previousSelections:summary};const prompt=await resolveActivePrompt("character_onboarding.character_identity_suggestions",context);const generated=await generateTextWithLlm({userId,householdId:input.householdId,taskType:"character_identity_suggestions",system:prompt.system,user:prompt.user,modelOverride:prompt.modelOverride,generationConfig:prompt.generationConfig});let suggestions:CharacterIdentitySuggestion[];try{suggestions=parse(generated.content)}catch(error){await getProfileDb().insert(aiGenerationTraces).values({id:crypto.randomUUID(),householdId:input.householdId,childProfileId:input.childProfileId,creationCycleId:cycle.id,taskType:"character_identity_suggestions",promptKey:prompt.promptKey,promptVersion:prompt.promptVersion,provider:generated.provider,modelId:generated.model,inputContext:context,outputPayload:{raw:generated.content},validationStatus:"invalid",promptTokens:generated.promptTokens,completionTokens:generated.completionTokens,totalTokens:generated.totalTokens,latencyMs:generated.latencyMs});throw error}await getProfileDb().insert(aiGenerationTraces).values({id:crypto.randomUUID(),householdId:input.householdId,childProfileId:input.childProfileId,creationCycleId:cycle.id,taskType:"character_identity_suggestions",promptKey:prompt.promptKey,promptVersion:prompt.promptVersion,provider:generated.provider,modelId:generated.model,inputContext:context,outputPayload:{suggestions},validationStatus:"valid",promptTokens:generated.promptTokens,completionTokens:generated.completionTokens,totalTokens:generated.totalTokens,latencyMs:generated.latencyMs});return {suggestions,trace:{promptKey:prompt.promptKey,promptVersion:prompt.promptVersion,provider:generated.provider,model:generated.model,promptTokens:generated.promptTokens,completionTokens:generated.completionTokens,totalTokens:generated.totalTokens,latencyMs:generated.latencyMs}}}
