"use client";

import { useMemo, useState } from "react";

type PromptVersion = { version: number; status: "draft" | "active" | "archived" };
type Preview = { system: string; user: string; usedVariables: string[]; missingRequiredVariables: string[]; unknownTemplateVariables: string[] };
type ModelRun = { version: number; status: string; output: string; parsedJson: unknown | null; provider: string; model: string; usage: { inputTokens: number | null; outputTokens: number | null; totalTokens: number | null }; latencyMs: number; estimatedCostUsd: number | null; schemaValidation: { valid: boolean; errors: string[] } };

export default function PromptPlayground({ promptKey, versions, selectedVersion }: { promptKey: string; versions: PromptVersion[]; selectedVersion: number }) {
  const active = useMemo(() => versions.find((item) => item.status === "active") ?? null, [versions]);
  const [contextText, setContextText] = useState("{}\n"); const [previews, setPreviews] = useState<{ active?: Preview; candidate?: Preview }>({}); const [runs, setRuns] = useState<{ active?: ModelRun; candidate?: ModelRun }>({}); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<"preview" | "model" | null>(null);
  function context() { const parsed = JSON.parse(contextText) as unknown; if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("Context bir JSON object olmalı."); return parsed as Record<string, unknown>; }
  async function request<T>(path: string, version: number, input: Record<string, unknown>) { const response = await fetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ promptKey, version, context: input }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message ?? "İşlem başarısız"); return payload.data as T; }
  async function runPreview() { setBusy("preview"); setError(null); try { const input = context(); const [activeResult, candidateResult] = await Promise.all([active ? request<Preview>("/api/settings/prompts/preview", active.version, input) : Promise.resolve(undefined), request<Preview>("/api/settings/prompts/preview", selectedVersion, input)]); setPreviews({ active: activeResult, candidate: candidateResult }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Preview çalıştırılamadı"); } finally { setBusy(null); } }
  async function runModel() { setBusy("model"); setError(null); try { const input = context(); const [activeResult, candidateResult] = await Promise.all([active ? request<ModelRun>("/api/settings/prompts/run", active.version, input) : Promise.resolve(undefined), request<ModelRun>("/api/settings/prompts/run", selectedVersion, input)]); setRuns({ active: activeResult, candidate: candidateResult }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Model çalıştırılamadı"); } finally { setBusy(null); } }
  return <div className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold text-slate-900">Prompt Playground</h3><p className="text-sm text-slate-600">Aynı context ile production active ve seçili sürümü karşılaştırın.</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={busy !== null} onClick={() => void runPreview()} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-800 disabled:opacity-50">{busy === "preview" ? "Hazırlanıyor…" : "Preview"}</button><button type="button" disabled={busy !== null} onClick={() => void runModel()} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy === "model" ? "Model çalışıyor…" : "Run with model"}</button></div></div><label className="block"><span className="mb-2 block text-sm font-semibold text-slate-800">Context JSON</span><textarea value={contextText} onChange={(event) => setContextText(event.target.value)} rows={9} spellCheck={false} className="w-full rounded-xl border border-slate-300 bg-white p-3 font-mono text-xs leading-5"/></label>{error ? <p className="mt-2 text-sm text-red-700">{error}</p> : null}</div>{(previews.active || previews.candidate) ? <section><h3 className="mb-2 text-sm font-semibold text-slate-700">Rendered prompt</h3><div className="grid gap-4 xl:grid-cols-2"><PreviewCard title={active ? `Production · v${active.version}` : "Production · active yok"} preview={previews.active}/><PreviewCard title={`Seçili · v${selectedVersion}`} preview={previews.candidate}/></div></section> : null}{(runs.active || runs.candidate) ? <section><h3 className="mb-2 text-sm font-semibold text-slate-700">Model sonucu</h3><div className="grid gap-4 xl:grid-cols-2"><RunCard title={active ? `Production · v${active.version}` : "Production · active yok"} run={runs.active}/><RunCard title={`Seçili · v${selectedVersion}`} run={runs.candidate}/></div></section> : null}</div>;
}
function PreviewCard({ title, preview }: { title: string; preview?: Preview }) { return <div className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4"><h4 className="mb-3 font-semibold text-slate-900">{title}</h4>{preview ? <div className="space-y-3">{(preview.missingRequiredVariables.length || preview.unknownTemplateVariables.length) ? <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">{preview.missingRequiredVariables.length ? <p>Eksik required: {preview.missingRequiredVariables.join(", ")}</p> : null}{preview.unknownTemplateVariables.length ? <p>İzinsiz variable: {preview.unknownTemplateVariables.join(", ")}</p> : null}</div> : <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-800">Variable kontrolü geçti.</div>}<Rendered label="System" value={preview.system}/><Rendered label="User" value={preview.user}/></div> : <p className="text-sm text-slate-500">Sonuç yok.</p>}</div>; }
function RunCard({ title, run }: { title: string; run?: ModelRun }) { return <div className="min-w-0 rounded-2xl border border-slate-200 bg-white p-4"><h4 className="mb-3 font-semibold text-slate-900">{title}</h4>{run ? <div className="space-y-3"><div className="grid grid-cols-2 gap-2 text-xs sm:grid-cols-5"><Metric label="Model" value={run.model}/><Metric label="Latency" value={`${run.latencyMs} ms`}/><Metric label="Tokens" value={run.usage.totalTokens?.toString() ?? "—"}/><Metric label="Cost" value={run.estimatedCostUsd == null ? "—" : `$${run.estimatedCostUsd.toFixed(6)}`}/><Metric label="Schema" value={run.schemaValidation.valid ? "✓ Valid" : "✗ Invalid"}/></div>{run.schemaValidation.valid ? <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-medium text-emerald-800">Output JSON Schema doğrulamasını geçti.</div> : <details className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-900"><summary className="cursor-pointer font-semibold">Schema validation başarısız · {run.schemaValidation.errors.length} hata</summary><ul className="mt-2 list-disc space-y-1 pl-5">{run.schemaValidation.errors.map((item) => <li key={item}>{item}</li>)}</ul></details>}<Rendered label="Output" value={run.output}/>{run.parsedJson !== null ? <Rendered label="Parsed JSON" value={JSON.stringify(run.parsedJson, null, 2)}/> : null}</div> : <p className="text-sm text-slate-500">Sonuç yok.</p>}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl bg-slate-50 p-2"><p className="text-slate-500">{label}</p><p className="truncate font-semibold text-slate-800" title={value}>{value}</p></div>; }
function Rendered({ label, value }: { label: string; value: string }) { return <div><p className="mb-1 text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><pre className="max-h-72 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-800">{value}</pre></div>; }
