import type { TestScenarioDefinition } from "./test-scenario";

const BOTH = ["character_first", "world_first"] as const;

export const CHARACTER_ONBOARDING_SCENARIO: TestScenarioDefinition = {
  key: "character_onboarding",
  label: "Character Onboarding",
  phases: [
    {
      id: "character_type",
      label: "Character Type",
      kind: "input",
      llmBacked: false,
      testable: false,
      productionOperation: "chooseCanonicalCharacterType",
      promptKey: null,
      directions: ["character_first"],
      requiredStateKeys: [],
      writesStateKey: "characterType",
    },
    {
      id: "character_first_identity_suggestions",
      label: "Character Identity Suggestions",
      kind: "generation",
      llmBacked: true,
      testable: true,
      productionOperation: "generateCharacterFirstIdentitySuggestions",
      promptKey: "character_onboarding.character_first_identity_suggestions",
      directions: ["character_first"],
      requiredStateKeys: ["characterType"],
      writesStateKey: "characterIdentity",
    },
    {
      id: "world_feeling",
      label: "World Feeling",
      kind: "input",
      llmBacked: false,
      testable: false,
      productionOperation: "chooseWorldFeeling",
      promptKey: null,
      directions: ["world_first"],
      requiredStateKeys: [],
      writesStateKey: "worldFeeling",
    },
    {
      id: "world_character_suggestions",
      label: "World Character Suggestions",
      kind: "generation",
      llmBacked: true,
      testable: true,
      productionOperation: "generateWorldCharacterSuggestions",
      promptKey: "character_onboarding.world_character_suggestions",
      directions: ["world_first"],
      requiredStateKeys: ["worldFeeling"],
      writesStateKey: "characterArchetype",
    },
    {
      id: "world_first_identity_suggestions",
      label: "Character Identity Suggestions",
      kind: "generation",
      llmBacked: true,
      testable: true,
      productionOperation: "generateCharacterIdentitySuggestions",
      promptKey: "character_onboarding.character_identity_suggestions",
      directions: ["world_first"],
      requiredStateKeys: ["worldFeeling", "characterArchetype"],
      writesStateKey: "characterIdentity",
    },
    {
      id: "universe",
      label: "Universe",
      kind: "input",
      llmBacked: false,
      testable: false,
      productionOperation: "chooseUniverse",
      promptKey: null,
      directions: ["character_first"],
      requiredStateKeys: ["characterIdentity"],
      writesStateKey: "universe",
    },
    {
      id: "world_suggestions",
      label: "World Suggestions",
      kind: "generation",
      llmBacked: true,
      testable: true,
      productionOperation: "generateWorldSuggestions",
      promptKey: "character_onboarding.world_suggestions",
      directions: ["character_first"],
      requiredStateKeys: ["characterIdentity", "universe"],
      writesStateKey: "world",
    },
    {
      id: "compatibility",
      label: "Character / World Compatibility",
      kind: "generation",
      llmBacked: true,
      testable: true,
      productionOperation: "generateCompatibilitySuggestions",
      promptKey: "character_onboarding.compatibility",
      directions: ["character_first"],
      requiredStateKeys: ["characterIdentity", "world"],
      writesStateKey: "compatibility",
    },
    {
      id: "region_suggestions",
      label: "Region Suggestions",
      kind: "generation",
      llmBacked: true,
      testable: true,
      productionOperation: "generateRegionSuggestions",
      promptKey: "character_onboarding.region_suggestions",
      directions: ["character_first"],
      requiredStateKeys: ["world", "compatibility"],
      writesStateKey: "region",
    },
    {
      id: "origin_suggestions",
      label: "Origin Suggestions",
      kind: "generation",
      llmBacked: true,
      testable: true,
      productionOperation: "generateCharacterOriginSuggestions",
      promptKey: "character_onboarding.character_origin_suggestions",
      directions: [...BOTH],
      requiredStateKeys: ["characterIdentity"],
      requiredStateKeysByDirection: {
        character_first: ["world", "region"],
        world_first: ["worldFeeling", "characterArchetype"],
      },
      writesStateKey: "origin",
    },
    {
      id: "core_saga",
      label: "Core Saga Suggestions",
      kind: "generation",
      llmBacked: true,
      testable: true,
      productionOperation: "generateCoreSagaSuggestions",
      promptKey: "character_onboarding.core_saga",
      directions: ["character_first"],
      requiredStateKeys: ["world", "region", "origin", "characterIdentity"],
      writesStateKey: "coreSaga",
    },
    {
      id: "final_review",
      label: "Final Review",
      kind: "finalize",
      llmBacked: false,
      testable: false,
      productionOperation: "finalizeCharacterFoundation",
      promptKey: null,
      directions: ["character_first"],
      requiredStateKeys: [
        "characterIdentity",
        "universe",
        "world",
        "region",
        "origin",
        "coreSaga",
      ],
      writesStateKey: null,
    },
  ],
};

export function onboardingTestablePhases() {
  return CHARACTER_ONBOARDING_SCENARIO.phases.filter((phase) => phase.testable);
}
