name: Bug report
description: Tekrarlanabilir bir LUMI hatasını bildirin.
title: "bug: "
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Açıklama
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Tekrarlama adımları
    validations:
      required: true
