import Link from "next/link";
export default async function CharacterStartDirectionPage({ params }: { params: Promise<{ childProfileId: string }> }) {
 const { childProfileId } = await params; const base=`/app/profiles/${encodeURIComponent(childProfileId)}/characters/new`;
 return <main className="min-h-screen bg-[#f8f4ea] px-4 py-8 text-[#34281f] sm:py-12"><section className="mx-auto max-w-5xl rounded-[32px] border border-[#e4d8c7] bg-[#fffdf7] p-5 shadow-sm sm:p-10">
 <p className="text-xs font-black uppercase tracking-[0.14em] text-[#1f7a70]">Yeni karakter · Başlangıç</p><h1 className="mt-3 max-w-2xl font-serif text-4xl font-black tracking-tight sm:text-5xl">Önce neyi hayal edelim?</h1>
 <p className="mt-4 max-w-2xl text-base leading-7 text-[#65584d]">İstersen karakterinden başlayalım, istersen önce yaşayacağı dünyayı keşfedelim. İki yol da sonunda aynı karakter hikâyesinde buluşacak.</p>
 <div className="mt-8 grid gap-4 md:grid-cols-2"><Link href={`${base}/type?direction=character_first`} className="rounded-[28px] border border-[#d9cbb8] bg-white p-6 transition hover:-translate-y-0.5 hover:shadow-md"><span className="text-4xl" aria-hidden="true">🧭</span><h2 className="mt-5 font-serif text-2xl font-black">Karakterimi seçmek istiyorum</h2><p className="mt-3 leading-7 text-[#65584d]">Karakteri seçelim; sonra ona yakışan dünyaları ve bölgeleri keşfedelim.</p><span className="mt-6 inline-flex font-extrabold text-[#1f7a70]">Karakterden başla →</span></Link>
 <Link href={`${base}/world-feeling?direction=world_first`} className="rounded-[28px] border border-[#d9cbb8] bg-white p-6 transition hover:-translate-y-0.5 hover:shadow-md"><span className="text-4xl" aria-hidden="true">🌎</span><h2 className="mt-5 font-serif text-2xl font-black">Dünyamı seçmek istiyorum</h2><p className="mt-3 leading-7 text-[#65584d]">Önce dünyanın doğasını seçelim; sonra oraya ait karakterler bulalım.</p><span className="mt-6 inline-flex font-extrabold text-[#1f7a70]">Dünyadan başla →</span></Link></div>
 <Link href={`/app/profiles/${encodeURIComponent(childProfileId)}`} className="mt-8 inline-flex rounded-2xl border border-[#dfd2be] bg-white px-5 py-3 font-extrabold text-[#51463d]">Vazgeç</Link></section></main>;
}
