-- Sprint 07: LLM-only character onboarding
-- Adds provenance columns to origin packages + backfills missing task configs
-- Forward-only additive migration.

BEGIN;

-- Add provenance columns to character_origin_packages
ALTER TABLE profile.character_origin_packages
  ADD COLUMN IF NOT EXISTS generation_batch_id UUID;

ALTER TABLE profile.character_origin_packages
  ADD COLUMN IF NOT EXISTS generation_source TEXT NOT NULL DEFAULT 'legacy_static';

ALTER TABLE profile.character_origin_packages
  ADD COLUMN IF NOT EXISTS model_id TEXT;

CREATE INDEX IF NOT EXISTS character_origin_packages_batch_idx
  ON profile.character_origin_packages (child_profile_id, generation_batch_id);

-- Mark all existing records as legacy_static (they were generated by deterministic fallback)
UPDATE profile.character_origin_packages
  SET generation_source = 'legacy_static'
  WHERE generation_source = 'legacy_static';

-- Backfill: create character_origin_generation task records for households
-- that have an OpenRouter provider key but no matching task config.
INSERT INTO profile.llm_task_model_settings (id, user_id, household_id, provider, task_type, model_id, reasoning_level, temperature, max_output_tokens, enabled, created_at, updated_at)
SELECT
  gen_random_uuid(),
  p.user_id,
  p.household_id,
  'openrouter',
  'character_origin_generation',
  'aion-labs/aion-3.0-mini',
  'medium',
  0.85,
  1800,
  true,
  NOW(),
  NOW()
FROM profile.llm_provider_settings p
WHERE p.provider = 'openrouter'
  AND p.encrypted_api_key IS NOT NULL
  AND LENGTH(p.encrypted_api_key) > 0
  AND NOT EXISTS (
    SELECT 1 FROM profile.llm_task_model_settings t
    WHERE t.user_id = p.user_id
      AND t.household_id = p.household_id
      AND t.task_type = 'character_origin_generation'
  )
ON CONFLICT DO NOTHING;

COMMIT;
